fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    registration:
        form:
            type: App\Form\RegistrationFormType
        confirmation:
            enabled: true
            from_email:
                address: "contact@kaisermall.tn"
                sender_name: "contact@kaisermall.tn"
    profile:
        form:
            type: App\Form\ProfileFormType  
    service:
        mailer: fos_user.mailer.twig_swift