dashboard_sliders_index:
    path: /list
    controller: App\Controller\Back\SlidersController::listAction
    
dashboard_sliders_details:
    path: /{id}/details
    controller: App\Controller\Back\SlidersController::showAction
    
dashboard_sliders_new:
    path: /new
    controller: App\Controller\Back\SlidersController::newAction   
    
dashboard_sliders_new_traitement:
    path: /new_traitement
    controller: App\Controller\Back\SlidersController::newTraitementAction
    
dashboard_sliders_edit:
    path: /{id}/edit
    controller: App\Controller\Back\SlidersController::editAction    
    
dashboard_sliders_edit_traitement:
    path: /{id}/edit_traitement
    controller: App\Controller\Back\SlidersController::editTraitementAction
    
dashboard_sliders_delete:
    path: /{id}/delete
    controller: App\Controller\Back\SlidersController::deleteAction    
