commercialstores_back_index:
    path: /list
    controller: App\Controller\Back\StoresBackController::listAction
   
commercialstores_back_new:
    path: /new
    controller: App\Controller\Back\StoresBackController::newAction   
    
commercialstores_back_new_traitement:
    path: /new_traitement
    controller: App\Controller\Back\StoresBackController::newTraitementAction      
    
commercialstores_back_details:
    path: /{id}/details
    controller: App\Controller\Back\StoresBackController::showAction
    
commercialstores_back_edit:
    path: /{id}/edit
    controller: App\Controller\Back\StoresBackController::editAction    
    
commercialstores_back_edit_traitement:
    path: /{id}/edit_traitement
    controller: App\Controller\Back\StoresBackController::editTraitementAction 
    
commercialstores_back_delete:
    path: /{id}/delete
    controller: App\Controller\Back\StoresBackController::deleteAction      
