manager_product_index:
    path: /list
    controller: App\Controller\Back\ProductBackController::liste
    
manager_product_index_by_store:
    path: /list/by_store/{id}
    controller: App\Controller\Back\ProductBackController::listeByStore    
    
manager_product_details:
    path: /{id}/details
    controller: App\Controller\Back\ProductBackController::details    
    
manager_product_back_new:
    path: /new
    controller: App\Controller\Back\ProductBackController::newAction
    
manager_product_back_new_by_store:
    path: /new/by_store/{id}
    controller: App\Controller\Back\ProductBackController::newByStoreAction    
    
manager_product_back_new_traitement:
    path: /new_traitement
    controller: App\Controller\Back\ProductBackController::newTraitementAction
    
manager_product_back_new_traitement_by_store:
    path: /new_traitement/{id}
    controller: App\Controller\Back\ProductBackController::newTraitementByStoreAction     
    
manager_product_back_edit:
    path: /{id}/edit
    controller: App\Controller\Back\ProductBackController::editAction
    
manager_product_back_edit_traitement:
    path: /{id}/edit_traitement
    controller: App\Controller\Back\ProductBackController::editTraitementAction
    
manager_product_delete:
    path: /{id}/delete
    controller: App\Controller\Back\ProductBackController:deleteAction    
    
manager_product_order_in_categorie:
    path: /product_order_in_categorie
    controller: App\Controller\Back\ProductBackController::productOrderInCategorie    
