api_product_details:
    path: /api-for-mobile/product-details/{slug}
    controller: App\Controller\Api\IndexController::productDetails

api_products_by_category:
    path: /api-for-mobile/products-by-category/{category}
    controller: App\Controller\Api\IndexController::productsByCategory